apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: wave-demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  APP_ENV: "production"
  DB_HOST: "database-svc"
  DB_PORT: "80"
  APP_VERSION: "1.0.0"